/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  new_fire_overrides_quiet_hours: Generated<boolean>;
  quiet_hours_end: Generated<string>;
  quiet_hours_start: Generated<string>;
  timezone: Generated<string>;
}

export interface AlertOutbox {
  actor_id: string | null;
  alert_subkey: string;
  alert_type: string;
  approval_mode: string | null;
  approved_at: Timestamp | null;
  approver_id: string | null;
  budget_override: Generated<boolean>;
  budget_seq: number | null;
  channel: string;
  channel_subscription_id: string | null;
  decided_at: Generated<Timestamp>;
  dispatched_at: Timestamp | null;
  fire_event_id: Int8;
  id: Generated<Int8>;
  last_error: string | null;
  priority: Generated<number>;
  provider_ack_at: Timestamp | null;
  pseudonymized_at: Timestamp | null;
  rule_version: string;
  status: string;
  template_id: string;
  template_params: Generated<Json>;
  trigger_ref_seq: Int8;
  trigger_type: string;
  watch_zone_id: string;
}

export interface AlertStates {
  escalation_watermark: Generated<number>;
  fire_event_id: Int8;
  last_notified_at: Timestamp | null;
  seeded_at: Timestamp | null;
  state: string;
  updated_at: Generated<Timestamp>;
  watch_zone_id: string;
}

export interface ChannelSubscriptions {
  account_id: string;
  channel: string;
  created_at: Generated<Timestamp>;
  endpoint: string;
  id: Generated<string>;
  revoked_at: Timestamp | null;
}

export interface ClusteringRuns {
  allow_revive: Generated<boolean>;
  config_digest: string;
  config_version: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  kind: string;
  params: Generated<Json>;
  promoted_at: Timestamp | null;
  window_end: Timestamp | null;
  window_start: Timestamp | null;
}

export interface Clusters {
  centroid: string;
  clustering_run_id: Int8;
  detection_count: Generated<number>;
  fire_event_id: Int8 | null;
  first_detection_at: Timestamp;
  hull: string | null;
  id: Generated<Int8>;
  last_detection_at: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface Detections {
  acq_ts: Timestamp;
  available_at: Timestamp;
  brightness_bg_k: number | null;
  brightness_k: number | null;
  collection_version: string | null;
  confidence: string;
  confidence_raw: string;
  day_night: string | null;
  detection_uid: string;
  footprint: string | null;
  frp_mw: number | null;
  geom: Generated<string | null>;
  ingest_config_version: string;
  ingested_at: Generated<Timestamp>;
  lat: Numeric;
  lon: Numeric;
  product_tier: string;
  /**
   * The ingest anomaly breaker tripped on the batch this row arrived in (TASKS C2). Set at insert time, never updated. Alerting skips these rows; the map and the archive do not — a false trip must not become permanent data loss.
   */
  quarantined: Generated<boolean>;
  scan_km: number | null;
  source: string;
  source_registry_version: string;
  track_km: number | null;
}

export interface EventDetections {
  acq_ts: Timestamp;
  attached_at: Generated<Timestamp>;
  clustering_run_id: Int8;
  detection_uid: string;
  fire_event_id: Int8;
}

export interface FireEvents {
  centroid: string;
  config_version: string;
  created_at: Generated<Timestamp>;
  detection_count: Generated<number>;
  display_tier: Generated<string>;
  hull: string | null;
  hull_diameter_km: number | null;
  id: Generated<Int8>;
  inactive_since: Timestamp | null;
  invalidated: Generated<boolean>;
  invalidated_reason: string | null;
  last_detection_at: Timestamp;
  max_frp_mw: number | null;
  merged_into: Int8 | null;
  miss_evidence: Generated<number>;
  nearest_place: Json | null;
  needs_review: Generated<boolean>;
  public_id: string;
  related_event_id: Int8 | null;
  relation_kind: string | null;
  score: Generated<number>;
  seq: Generated<Int8>;
  source_mix: Generated<Json>;
  source_registry_version: string;
  split_from: Int8 | null;
  started_at: Timestamp;
  status: string;
  status_changed_at: Timestamp;
  status_reason: string | null;
  sum_frp_mw: number | null;
  updated_at: Generated<Timestamp>;
}

export interface IngestBatches {
  already_present: number;
  anomaly_tripped: boolean;
  anomaly_verdict: string;
  available_at: Timestamp;
  baseline: Numeric | null;
  ingest_config_version: string;
  inserted: number;
  polling_bbox_version: string;
  quarantined: number;
  ratio: Numeric | null;
  received: number;
  recorded_at: Generated<Timestamp>;
  rejected: number;
  source: string;
  source_registry_version: string;
}

export interface IngestQuarantine {
  available_at: Timestamp;
  detection_uid: string | null;
  id: Generated<Int8>;
  raw: string | null;
  reason: string;
  recorded_at: Generated<Timestamp>;
  row_index: number | null;
  scope: string;
  source: string;
}

export interface Sources {
  attach_only: boolean;
  id: string;
  product_tier: string | null;
  queried_product: string;
  status: string;
  status_effective_from: Timestamp;
}

export interface SourceStatus {
  consecutive_failures: Generated<number>;
  last_attempt_at: Timestamp | null;
  last_data_at: Timestamp | null;
  last_error: string | null;
  last_success_at: Timestamp | null;
  outage_frozen: Generated<boolean>;
  source: string;
  updated_at: Generated<Timestamp>;
}

export interface TableBackupClass {
  class: string;
  note: string | null;
  table_name: string;
}

export interface WatchZones {
  account_id: string;
  area: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  min_score: Generated<number>;
  name: string;
  radius_m: number | null;
}

export interface DB {
  accounts: Accounts;
  alert_outbox: AlertOutbox;
  alert_states: AlertStates;
  channel_subscriptions: ChannelSubscriptions;
  clustering_runs: ClusteringRuns;
  clusters: Clusters;
  detections: Detections;
  event_detections: EventDetections;
  fire_events: FireEvents;
  ingest_batches: IngestBatches;
  ingest_quarantine: IngestQuarantine;
  source_status: SourceStatus;
  sources: Sources;
  table_backup_class: TableBackupClass;
  watch_zones: WatchZones;
}
