/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string | null;
  email_verified_at: Timestamp | null;
  id: Generated<string>;
  new_fire_overrides_quiet_hours: Generated<boolean>;
  quiet_hours_end: Generated<string>;
  quiet_hours_start: Generated<string>;
  timezone: Generated<string>;
}

export interface AccountSessions {
  account_id: string;
  created_at: Timestamp;
  expires_at: Timestamp;
  id: Generated<string>;
  last_seen_at: Timestamp;
  revoked_at: Timestamp | null;
  token_hash: Buffer;
  ua_family: string;
}

export interface AlertDecisionLog {
  alert_type: string | null;
  code: string;
  decided_at: Timestamp;
  fire_event_id: Int8;
  id: Generated<Int8>;
  in_quiet_hours: boolean;
  ladder_step: number;
  outcome: string;
  pass: string;
  reason: string;
  recorded_at: Generated<Timestamp>;
  rule_version: string;
  trigger_ref_seq: Int8;
  watch_zone_id: string;
}

export interface AlertDigestLog {
  decided_at: Timestamp;
  entry_count: number;
  id: Generated<Int8>;
  outcome: string;
  reason: string;
  recorded_at: Generated<Timestamp>;
  rule_version: string;
  watch_zone_id: string;
  window_start: Timestamp;
}

export interface AlertEvaluatedEvents {
  evaluated_at: Timestamp;
  fire_event_id: Int8;
  last_seq: Int8;
  last_status: string;
}

export interface AlertEvaluationCursor {
  id: number;
  last_seq: Int8;
  updated_at: Timestamp;
}

export interface AlertOutbox {
  /**
   * A1.1: the human who initiated a manual send. NULL on automatic rows.
   */
  actor_id: string | null;
  alert_subkey: string;
  alert_type: string;
  approval_mode: string | null;
  approved_at: Timestamp | null;
  approver_id: string | null;
  /**
   * A1.1/D5: the row was released past budget B by a human.
   */
  budget_override: Generated<boolean>;
  budget_seq: number | null;
  channel: string;
  channel_subscription_id: string | null;
  claimed_at: Timestamp | null;
  decided_at: Generated<Timestamp>;
  dispatched_at: Timestamp | null;
  fire_event_id: Int8;
  id: Generated<Int8>;
  last_error: string | null;
  locale: Generated<string>;
  priority: Generated<number>;
  provider_ack_at: Timestamp | null;
  pseudonymized_at: Timestamp | null;
  rule_version: string;
  status: string;
  template_id: string;
  template_params: Generated<Json>;
  trigger_ref_seq: Int8;
  /**
   * A1.1 four-value provenance: what caused the row. Equals alert_type on automatic rows.
   */
  trigger_type: string;
  watch_zone_id: string | null;
}

export interface AlertsShadow {
  alert_subkey: string;
  alert_type: string;
  candidate_version: string;
  decided_at: Timestamp;
  recorded_at: Generated<Timestamp>;
  rule_version: string;
  shadow_event_key: string;
  template_id: string;
  template_params: Generated<Json>;
  trigger_type: string;
  watch_zone_id: string;
}

export interface AlertStates {
  escalation_watermark: Generated<number>;
  fire_event_id: Int8;
  last_notified_at: Timestamp | null;
  seeded_at: Timestamp | null;
  state: string;
  updated_at: Generated<Timestamp>;
  watch_zone_id: string;
}

export interface AuthLinkRequests {
  consumed_at: Timestamp | null;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  requested_at: Timestamp;
  superseded_at: Timestamp | null;
  token_hash: Buffer;
  ua_family: string;
}

export interface ChannelConfirmations {
  account_id: string;
  channel: string;
  channel_subscription_id: string | null;
  consumed_at: Timestamp | null;
  expires_at: Timestamp;
  id: Generated<string>;
  issued_at: Timestamp;
  revoked_at: Timestamp | null;
  superseded_at: Timestamp | null;
  token_hash: Buffer;
}

export interface ChannelSubscriptions {
  account_id: string;
  channel: string;
  confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  endpoint: string;
  id: Generated<string>;
  revoked_at: Timestamp | null;
}

export interface ClusteringBatches {
  already_assigned: number;
  attached: number;
  /**
   * available_at of the ingest batch, as stamped on its detections. Also the engine batch instant.
   */
  available_at: Timestamp;
  /**
   * Wall-clock time of the commit that clustered the batch. Operational only; no rule reads it.
   */
  clustered_at: Generated<Timestamp>;
  clustering_run_id: Int8;
  /**
   * ClusterBatchResult.stats.detections: non-quarantined rows handed to the engine.
   */
  detections: number;
  merged: number;
  seeded: number;
  /**
   * Source of the ingest batch (ingest_batches key, with available_at).
   */
  source: string;
  unattached: number;
}

export interface ClusteringRuns {
  allow_revive: Generated<boolean>;
  config_digest: string;
  config_version: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  kind: string;
  /**
   * Instant of the previous lifecycle tick over this run's events; the start of the next evidence window.
   */
  lifecycle_ticked_at: Timestamp | null;
  params: Generated<Json>;
  promoted_at: Timestamp | null;
  window_end: Timestamp | null;
  window_start: Timestamp | null;
}

export interface Clusters {
  centroid: string;
  clustering_run_id: Int8;
  detection_count: Generated<number>;
  fire_event_id: Int8 | null;
  first_detection_at: Timestamp;
  hull: string | null;
  id: Generated<Int8>;
  last_detection_at: Timestamp;
  /**
   * Instant the public_id was minted (the engine batch instant). Its UTC year is the cosmetic fw-YYYY.
   */
  minted_at: Timestamp;
  /**
   * Detection the cluster was created by; the frozen seed of its public_id. Never changes.
   */
  seed_detection_uid: string;
  updated_at: Generated<Timestamp>;
}

export interface Detections {
  acq_ts: Timestamp;
  available_at: Timestamp;
  brightness_bg_k: number | null;
  brightness_k: number | null;
  collection_version: string | null;
  confidence: string;
  confidence_raw: string;
  day_night: string | null;
  detection_uid: string;
  footprint: string | null;
  frp_mw: number | null;
  geom: Generated<string | null>;
  ingest_config_version: string;
  ingested_at: Generated<Timestamp>;
  lat: Numeric;
  lon: Numeric;
  product_tier: string;
  /**
   * The ingest anomaly breaker tripped on the batch this row arrived in (TASKS C2). Set at insert time, never updated. Alerting skips these rows; the map and the archive do not — a false trip must not become permanent data loss.
   */
  quarantined: Generated<boolean>;
  scan_km: number | null;
  source: string;
  source_registry_version: string;
  track_km: number | null;
}

export interface ErasureRequests {
  account_hash: Buffer;
  counts: Json;
  deadline_at: Timestamp;
  erased_at: Timestamp;
  plan_version: string;
}

export interface EventDetections {
  acq_ts: Timestamp;
  attached_at: Generated<Timestamp>;
  clustering_run_id: Int8;
  detection_uid: string;
  fire_event_id: Int8;
}

export interface EventsShadow {
  candidate_config_digest: string;
  candidate_version: string;
  detection_uids: string[];
  invalidated: Generated<boolean>;
  last_detection_at: Timestamp;
  merged_into_key: string | null;
  recorded_at: Generated<Timestamp>;
  score: number;
  shadow_key: string;
  started_at: Timestamp;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface FireEvents {
  centroid: string;
  config_version: string;
  created_at: Generated<Timestamp>;
  detection_count: Generated<number>;
  /**
   * Read surface (ADR-002 D6 display tiers): map = active set served by /snapshot.json, feed = list only, archive. Written by lifecycle transitions, never derived at read time (ADR-003 A1.4 R1).
   */
  display_tier: Generated<string>;
  /**
   * UTC midnight of the day geo_weight_spent belongs to. NULL with geo_weight_spent when no GEO weight was carried.
   */
  geo_weight_day: Timestamp | null;
  /**
   * GEO miss weight already spent on geo_weight_day (the daily cap balance). Bookkeeping: never bumps seq.
   */
  geo_weight_spent: number | null;
  hull: string | null;
  hull_diameter_km: number | null;
  id: Generated<Int8>;
  /**
   * Instant of the transition out of active/signal_weakening that the time rules count from (A2.2). NULL while active or weakening.
   */
  inactive_since: Timestamp | null;
  invalidated: Generated<boolean>;
  invalidated_reason: string | null;
  last_detection_at: Timestamp;
  /**
   * UTC midnight the event's current run of observation-free days is counted from; NULL until the first lifecycle tick. Bookkeeping: never bumps seq.
   */
  lifecycle_blind_since: Timestamp | null;
  /**
   * Newest acquisition the previous lifecycle tick knew about; NULL until the first tick. The redetection test compares against it.
   */
  lifecycle_seen_detection_at: Timestamp | null;
  max_frp_mw: number | null;
  merged_into: Int8 | null;
  /**
   * Accumulated miss evidence E carried between lifecycle ticks (ADR-002 D4). Bookkeeping: never bumps seq.
   */
  miss_evidence: Generated<number>;
  nearest_place: Json | null;
  needs_review: Generated<boolean>;
  public_id: string;
  related_event_id: Int8 | null;
  relation_kind: string | null;
  score: Generated<number>;
  /**
   * score_params version that produced score (ADR-002 D5/D6); NULL = never scored (tombstone, absorbed seed, or not touched since 017). Bookkeeping: never bumps seq.
   */
  score_params_version: string | null;
  seq: Generated<Int8>;
  source_mix: Generated<Json>;
  source_registry_version: string;
  split_from: Int8 | null;
  started_at: Timestamp;
  status: string;
  status_changed_at: Timestamp;
  status_reason: string | null;
  sum_frp_mw: number | null;
  updated_at: Generated<Timestamp>;
}

export interface FireEventTransitions {
  fire_event_id: Int8;
  from_status: string | null;
  hull_area_ha: number | null;
  id: Generated<Int8>;
  max_frp_mw: number | null;
  recorded_at: Generated<Timestamp>;
  seq: Int8;
  status_reason: string | null;
  to_status: string;
  transitioned_at: Timestamp;
}

export interface IngestBatches {
  already_present: number;
  anomaly_tripped: boolean;
  anomaly_verdict: string;
  available_at: Timestamp;
  baseline: Numeric | null;
  ingest_config_version: string;
  inserted: number;
  polling_bbox_version: string;
  quarantined: number;
  ratio: Numeric | null;
  received: number;
  recorded_at: Generated<Timestamp>;
  rejected: number;
  source: string;
  source_registry_version: string;
}

export interface IngestQuarantine {
  available_at: Timestamp;
  detection_uid: string | null;
  id: Generated<Int8>;
  raw: string | null;
  reason: string;
  recorded_at: Generated<Timestamp>;
  row_index: number | null;
  scope: string;
  source: string;
}

export interface LifecycleLogOrigin {
  id: number;
  started_at: Timestamp;
}

export interface NrtLagHistograms {
  below: number;
  computed_at: Generated<Timestamp>;
  counts: number[];
  day: Timestamp;
  edges_minutes: number[];
  histogram_digest: string;
  histogram_version: string;
  max_lag_ms: Int8 | null;
  min_lag_ms: Int8 | null;
  overflow: number;
  source: string;
  total: number;
}

export interface QaWeeklyReports {
  generated_at: Timestamp;
  iso_week: string;
  metrics_digest: string;
  metrics_version: string;
  report_digest: string;
  report_json: string;
  report_markdown: string;
  report_version: string;
  window_end: Timestamp;
  window_start: Timestamp;
  written_at: Generated<Timestamp>;
}

export interface Sources {
  attach_only: boolean;
  id: string;
  product_tier: string | null;
  queried_product: string;
  status: string;
  status_effective_from: Timestamp;
}

export interface SourceStatus {
  consecutive_failures: Generated<number>;
  last_attempt_at: Timestamp | null;
  last_data_at: Timestamp | null;
  last_error: string | null;
  last_success_at: Timestamp | null;
  outage_frozen: Generated<boolean>;
  source: string;
  updated_at: Generated<Timestamp>;
}

export interface TableBackupClass {
  class: string;
  note: string | null;
  table_name: string;
}

export interface WatchZones {
  account_id: string;
  area: string | null;
  centre_ciphertext: Buffer | null;
  centre_coarsened: boolean | null;
  centre_key_id: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  grid_cell: string | null;
  grid_version: string | null;
  id: Generated<string>;
  min_score: Generated<number>;
  name: string;
  radius_m: number | null;
}

export interface DB {
  account_sessions: AccountSessions;
  accounts: Accounts;
  alert_decision_log: AlertDecisionLog;
  alert_digest_log: AlertDigestLog;
  alert_evaluated_events: AlertEvaluatedEvents;
  alert_evaluation_cursor: AlertEvaluationCursor;
  alert_outbox: AlertOutbox;
  alert_states: AlertStates;
  alerts_shadow: AlertsShadow;
  auth_link_requests: AuthLinkRequests;
  channel_confirmations: ChannelConfirmations;
  channel_subscriptions: ChannelSubscriptions;
  clustering_batches: ClusteringBatches;
  clustering_runs: ClusteringRuns;
  clusters: Clusters;
  detections: Detections;
  erasure_requests: ErasureRequests;
  event_detections: EventDetections;
  events_shadow: EventsShadow;
  fire_event_transitions: FireEventTransitions;
  fire_events: FireEvents;
  ingest_batches: IngestBatches;
  ingest_quarantine: IngestQuarantine;
  lifecycle_log_origin: LifecycleLogOrigin;
  nrt_lag_histograms: NrtLagHistograms;
  qa_weekly_reports: QaWeeklyReports;
  source_status: SourceStatus;
  sources: Sources;
  table_backup_class: TableBackupClass;
  watch_zones: WatchZones;
}
